### ISSUE TITLE
requires a version of quark that doesn't exist

### ISSUE THREAD

**Issue by PODEPOM** [jbredwards/Piston-API-Mod#1]
this mod, which is specifically made for 1.12.2,  says it's only compatible with quark version 1.6-180, but the most recent build of quark made for 1.12.2 is 1.6-179

How can this mod demand a version of another mod that doesn't exist? What do I do?

**Comment by jbredwards** [comment]
whoops lol, apparently the version of quark on their git page (r1.6-180) is unreleased :P, fixed in v1.0.1
